### PR TITLE
Scatter bindings

### PR DESCRIPTION
**Pull request by gboduljak**
## Proposed changes

Implemented ``scatter_{op}`` bindings and added some trivial tests.
We still need to improve documentation by providing useful examples and detailed description of scatter operations. We also need more tests for more interesting ``scatter_{op}`` cases.

## Checklist

Put an `x` in the boxes that apply.

- [x] I have read the [CONTRIBUTING](https://github.com/ml-explore/mlx/blob/main/CONTRIBUTING.md) document
- [x] I have run `pre-commit run --all-files` to format my code / installed pre-commit prior to committing changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation (if needed)

### CODE REVIEW

**Review by francescofarina — APPROVED** [review]
Looks great! Can't currently test it locally because of https://github.com/ml-explore/mlx/issues/396 - so let's merge and perhaps iterate on tests later

**Comment by gboduljak** [comment]
> Looks great! Can't currently test it locally because of [ml-explore#396](https://github.com/ml-explore/mlx/issues/396) - so let's merge and perhaps iterate later

Let's hope this is resolved soon :)

**Comment by francescofarina** [comment]
@gboduljak feel free to merge whenever

**Comment by gboduljak** [comment]
> @gboduljak feel free to merge whenever

I do not have permissions.

**Comment by francescofarina** [comment]
Ah right, apologies, merging now ;)

**Pull request merged**
